"""create ownership table

Revision ID: 14b505913f0e
Revises: 1254cfefd50a
Create Date: 2026-08-30 18:04:37.921633

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '14b505913f0e'
down_revision: str | Sequence[str] | None = '1254cfefd50a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ownership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('owner_sequence', sa.Integer(), nullable=False),
    sa.Column('owner_name', sa.String(length=150), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('transfer_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ownership_vehicle_id'), 'ownership', ['vehicle_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ownership_vehicle_id'), table_name='ownership')
    op.drop_table('ownership')
    # ### end Alembic commands ###
